# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(blank=True, default='', max_length=100)),
                ('verb', models.CharField(blank=True, default='', max_length=100)),
                ('object', models.CharField(blank=True, default='', max_length=100)),
                ('text', models.CharField(blank=True, default='', max_length=250)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
